module.exports = {
  atlanta: {
    geojsonUrl: 'https://s3.amazonaws.com/civics.city/atlanta/data/council-districts.geojson',
    repesentativeDistrictTerm: 'city council district',
    '1': '@JasonHWinston',
    '2': '@AmirForATL',
    '3': '@ByronAmos',
    '4': '@jasonsdozier',
    '5': '@LilianaforATL',
    '6': '@AlexWanforATL',
    '7': 'Howard Shook',
    '8': '@marynorwood',
    '9': '@Dustin4ATL',
    '10': '@AndreaBooneNow',
    '11': '@MarciOverstreet',
    '12': '@antoniolewisatl',
    atLarge: ['@Michael_J_Bond', '@WestmorelandATL', '@WaitesKeisha', '@DougShipmanATL'],
  },
  RVA: {
    geojsonUrl: 'using.local.file.for.this.location',
    list: ['@DPW_RichmondVA', '@LevarStoney', '@andreasrva', '@KatherineJRVA', '@AnnCan2020', '@kristenRVA',
      '@Stephanie4RVA', '@ellenrva', '@CynthiaNewbille', '@TrammellReva', '@thedrmikejones'],
    repesentativeDistrictTerm: 'city council district',
    '1': 'Andreas D. Addison @andreasrva',
    '2': 'Katherine Jordan @KatherineJRVA',
    '3': 'Ann-Frances Lambert @AnnCan2020',
    '4': 'Kristen M. Nye @kristenRVA',
    '5': 'Stephanie A. Lynch @Stephanie4RVA',
    '6': 'Ellen F. Robertson @ellenrva',
    '7': 'Cynthia I. Newbille @CynthiaNewbille',
    '8': 'Reva M. Trammell @TrammellReva',
    '9': 'Michael J. Jones @thedrmikejones',
  },
  Philly: {
    geojsonUrl: 'using.local.file.for.this.location',
    list: ['@PhillyMayor', '@Darrell_Clarke', '@marksquilla', '@CouncilmemberKJ', '@CouncilmemberJG', '@Mr_4thDistrict', '@RepDriscoll',
      '@cindybassphilly', '@ONeill4NEPhilly', '@KendraPHL', '@Kathy_Gilmore', '@HelenGymPHL', '@DavidOhPhilly',
      '@CMThomasPHL'],
    repesentativeDistrictTerm: 'city council district',
    '1': 'Mark Squilla @marksquilla',
    '2': 'Kenyatta Johnson @CouncilmemberKJ',
    '3': 'Jamie Gauthier @CouncilmemberJG',
    '4': 'Curtis Jones, Jr. @Mr_4thDistrict',
    '5': 'Darrell Clarke @Darrell_Clarke',
    '6': 'Mike Driscoll @RepDriscoll',
    '7': 'Quetzy Lozada @Quetcy @LozadaQuetcy',
    '8': 'Cindy Bass @cindybassphilly',
    '9': 'Anthony Phillips',
    '10': 'Brian J. Oneill @ONeill4NEPhilly',
  },
  KC: {
    geojsonUrl: 'using.local.file.for.this.location',
    list: ['@MayorLucasKc', '@Hall1stDistrict', '@HeatherHallKC', '@KOneillkcmo', '@TeresaLoar', '@DanFowlerKCMO',
      '@ellington_b', '@Robinson4kc', '@K_J_Shields', '@EricWBunch', '#LeeBarnes', '@mcmanuskc', '@Ryana4KC',
      '@AndreaBough', '@BrianDavidPlatt', '@WaldronKC', '@MShawKC'],
    repesentativeDistrictTerm: 'city council district',
    '1': "Heather Hall @Hall1stDistrict @HeatherHallKC and Kevin O'Neill @KOneillkcmo at-large",
    '2': "Dan Fowler @DanFowlerKCMO and Teresa Loar @TeresaLoar at-large",
    '3': "Melissa Robinson @Robinson4kc and Brandon Ellington @ellington_b at-large",
    '4': "Eric Bunch @EricWBunch and Katheryn Shields @K_J_Shields at-large",
    '5': "Ryana Parks-Shaw @Ryana4KC and Lee Barnes, Jr #LeeBarnes at-large",
    '6': "Kevin McManus @mcmanuskc and Andrea Bough @AndreaBough at-large"
  }
};
